In [89]:
import pandas as pd
import os as os
import numpy as np
import talib as talib
import json as json
pd.options.mode.chained_assignment = None

In [90]:
# 1.0
path1 = os.path.abspath(os.path.join('data', 'nq', 'prediction', 't5-0608-0922-e12-u512-w50.csv'))
path1 = os.path.abspath(os.path.join('data', 'nq', 'prediction', 't5-0608-0922-e10-u512-w50.csv'))
df1 = pd.read_csv(path1)
df1.udate = pd.to_datetime(df1.udate)
df1.index = pd.to_datetime(df1.udate)
df1

,udate,High,Low,Open,Close,Volume,t1,t2,t3,t4,t5
udate,,,,,,,,,,,
2020-06-08 17:00:00,2020-06-08 17:00:00,9865.50,9865.50,9865.50,9865.50,0.0,NaN,NaN,NaN,NaN,NaN
2020-06-08 17:01:00,2020-06-08 17:01:00,9865.50,9865.50,9865.50,9865.50,0.0,NaN,NaN,NaN,NaN,NaN
2020-06-08 17:02:00,2020-06-08 17:02:00,9860.25,9860.50,9859.25,9859.50,5.0,NaN,NaN,NaN,NaN,NaN
2020-06-08 17:03:00,2020-06-08 17:03:00,9859.50,9860.00,9857.50,9857.50,12.0,NaN,NaN,NaN,NaN,NaN
2020-06-08 17:04:00,2020-06-08 17:04:00,9857.50,9859.25,9857.50,9859.25,1.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2020-09-22 15:49:00,2020-09-22 15:49:00,11149.75,11150.50,11149.50,11149.75,23.0,11160.756373,11160.998925,11161.330512,11162.469866,11160.782499
2020-09-22 15:50:00,2020-09-22 15:50:00,11149.75,11151.75,11148.50,11151.75,77.0,11160.650260,11160.898649,11161.228754,11162.370856,11160.659617
2020-09-22 15:51:00,2020-09-22 15:51:00,11151.75,11152.50,11150.75,11151.25,43.0,11161.214671,11161.443666,11161.781090,11162.924953,11161.205376
2020-09-22 15:52:00,2020-09-22 15:52:00,11151.25,11152.00,11150.25,11151.00,17.0,11162.149520,11162.357391,11162.700621,11163.847171,11162.128149
2020-09-22 15:53:00,2020-09-22 15:53:00,11151.00,11153.00,11151.00,11152.25,13.0,11163.264261,11163.458204,11163.803595,11164.954561,11163.240110

In [91]:
# 2.0
df2 = df1.copy(deep=True)

highs = np.array(df2['High'], dtype='float')
lows = np.array(df2['Low'], dtype='float')
opens = np.array(df2['Open'], dtype='float')
closes = np.array(df2['Close'], dtype='float')
vols = np.array(df2['Volume'], dtype='float')
df2['atr'] = talib.ATR(highs, lows, closes, timeperiod=14*2)

df2['last1'] = df2['Close'].shift(periods=-1) # 上笔数据 最后价
df2['adjust'] = df2['Close'] - df2['t5'] # 5分钟后的 波幅
df2['pchange1'] = (df2['t1'] - df2['Close']) / df2['Close']*100 # 1分钟后的 波幅率
df2['pchange'] = (df2['t5'] - df2['Close']) / df2['Close']*100 # 5分钟后的 波幅率
df2

,udate,High,Low,Open,Close,Volume,t1,t2,t3,t4,t5,atr,last1,adjust,pchange1,pchange
udate,,,,,,,,,,,,,,,,
2020-06-08 17:00:00,2020-06-08 17:00:00,9865.50,9865.50,9865.50,9865.50,0.0,NaN,NaN,NaN,NaN,NaN,NaN,9865.50,NaN,NaN,NaN
2020-06-08 17:01:00,2020-06-08 17:01:00,9865.50,9865.50,9865.50,9865.50,0.0,NaN,NaN,NaN,NaN,NaN,NaN,9859.50,NaN,NaN,NaN
2020-06-08 17:02:00,2020-06-08 17:02:00,9860.25,9860.50,9859.25,9859.50,5.0,NaN,NaN,NaN,NaN,NaN,NaN,9857.50,NaN,NaN,NaN
2020-06-08 17:03:00,2020-06-08 17:03:00,9859.50,9860.00,9857.50,9857.50,12.0,NaN,NaN,NaN,NaN,NaN,NaN,9859.25,NaN,NaN,NaN
2020-06-08 17:04:00,2020-06-08 17:04:00,9857.50,9859.25,9857.50,9859.25,1.0,NaN,NaN,NaN,NaN,NaN,NaN,9859.00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-22 15:49:00,2020-09-22 15:49:00,11149.75,11150.50,11149.50,11149.75,23.0,11160.756373,11160.998925,11161.330512,11162.469866,11160.782499,2.762027,11151.75,-11.032499,0.098714,0.098948
2020-09-22 15:50:00,2020-09-22 15:50:00,11149.75,11151.75,11148.50,11151.75,77.0,11160.650260,11160.898649,11161.228754,11162.370856,11160.659617,2.734812,11151.25,-8.909617,0.079810,0.079894
2020-09-22 15:51:00,2020-09-22 15:51:00,11151.75,11152.50,11150.75,11151.25,43.0,11161.214671,11161.443666,11161.781090,11162.924953,11161.205376,2.663926,11151.00,-9.955376,0.089359,0.089276
2020-09-22 15:52:00,2020-09-22 15:52:00,11151.25,11152.00,11150.25,11151.00,17.0,11162.149520,11162.357391,11162.700621,11163.847171,11162.128149,2.595571,11152.25,-11.128149,0.099987,0.099795
2020-09-22 15:53:00,2020-09-22 15:53:00,11151.00,11153.00,11151.00,11152.25,13.0,11163.264261,11163.458204,11163.803595,11164.954561,11163.240110,2.574301,NaN,-10.990110,0.098763,0.098546

In [127]:
# 3.0
direction = 'long' # 方向
vol = 0.45 # 买卖波幅
vol2 = 0 # 止蚀波幅
cutloss = 1.05 # 止蚀

# 3.1
df4 = pd.DataFrame(columns = ['udate', 'action', 'cash', 'profit', 'message'])
holding = False # 是否持有仓位
top_profit_price = 0 # 买入点数
fee = 2.1 # 交易费
cash = 0

def is_trigger(v2, vol):
    if direction == 'long':
        return (v2['pchange'] >= vol)
    elif direction == 'short':
        return (v2['pchange'] <= -vol)

def is_cut_loss(v2, top_profit_price, direction):
    if direction == 'long':
        return (abs(v1['Close']-top_profit_price) >= abs(cutloss*v1['atr']))
    elif direction == 'short':
        return (abs(top_profit_price-v1['Close']) >= abs(cutloss*v1['atr']))
    
def is_stop_profit(v2, vol2):
    if direction == 'long':
        return (v2['pchange1'] <= vol2)
    elif direction == 'short':
        return (v2['pchange1'] >= vol2)

df3 = df2.copy(deep=True)
for k1, v1 in df3.iterrows():
    if v1['udate'].hour < 15 or v1['udate'].hour >= 19:
        # 3.2 买入
        if is_trigger(v1, vol) and not holding:
            holding = True
            cost1 = v1['Close']
            top_profit_price = v1['Close']
            action = 'buy' if direction == 'long' else 'sell'
            df4 = df4.append({'udate': k1, 'action': action, 'cash': np.nan, 'profit': np.nan, 'message': np.nan}, ignore_index=True)
            continue
        # 3.3
        cut_loss2 = is_cut_loss(v1, top_profit_price, direction) # 止蚀
        stop_profit2 = is_stop_profit(v1, vol2) # 止盈
        if (cut_loss2 or stop_profit2) and holding:
            holding = False
            profit2 = (v1['Close']-cost1)*20 - (fee*2)
            cash = cash + profit2
            # 3.4 长仓
            if direction == 'long' and stop_profit2:
                action = 'sell'
            elif direction == 'long' and cut_loss2:
                action = 'cut'
            # 3.5 短仓
            elif direction == 'short' and stop_profit2:
                action = 'buy'
            elif direction == 'short' and cut_loss2:
                action = 'cut'
            df4 = df4.append({'udate': k1, 'action': action, 'cash': cash, 'profit': profit2, 'message': np.nan}, ignore_index=True)
        
df4.index = df4['udate']
df4.drop(['udate'], axis=1, inplace=True)
df4

                    action     cash  profit  message
udate
2020-06-10 14:02:00    buy      NaN     NaN      NaN
2020-06-10 14:03:00    cut    235.8   235.8      NaN
2020-06-11 08:38:00    buy      NaN     NaN      NaN
2020-06-11 08:39:00    cut    336.6   100.8      NaN
2020-06-11 09:59:00    buy      NaN     NaN      NaN
...                    ...      ...     ...      ...
2020-09-16 14:11:00    cut  12555.8  -179.2      NaN
2020-09-16 14:32:00    buy      NaN     NaN      NaN
2020-09-16 14:33:00    cut  12786.6   230.8      NaN
2020-09-17 09:25:00    buy      NaN     NaN      NaN
2020-09-17 09:28:00    cut  13107.4   320.8      NaN

[756 rows x 4 columns]

In [128]:
# 4.0
df5 = pd.concat([df2, df4], axis=1)
drop_list_5 = ['High', 'Low', 'Open', 'Volume', 't2', 't3', 't4']
df5.drop(drop_list_5, axis=1, inplace=True)
df5

,udate,Close,t1,t5,atr,last1,adjust,pchange1,pchange,action,cash,profit,message
udate,,,,,,,,,,,,,
2020-06-08 17:00:00,2020-06-08 17:00:00,9865.50,NaN,NaN,NaN,9865.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-06-08 17:01:00,2020-06-08 17:01:00,9865.50,NaN,NaN,NaN,9859.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-06-08 17:02:00,2020-06-08 17:02:00,9859.50,NaN,NaN,NaN,9857.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-06-08 17:03:00,2020-06-08 17:03:00,9857.50,NaN,NaN,NaN,9859.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-06-08 17:04:00,2020-06-08 17:04:00,9859.25,NaN,NaN,NaN,9859.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-22 15:49:00,2020-09-22 15:49:00,11149.75,11160.756373,11160.782499,2.762027,11151.75,-11.032499,0.098714,0.098948,NaN,NaN,NaN,NaN
2020-09-22 15:50:00,2020-09-22 15:50:00,11151.75,11160.650260,11160.659617,2.734812,11151.25,-8.909617,0.079810,0.079894,NaN,NaN,NaN,NaN
2020-09-22 15:51:00,2020-09-22 15:51:00,11151.25,11161.214671,11161.205376,2.663926,11151.00,-9.955376,0.089359,0.089276,NaN,NaN,NaN,NaN
2020-09-22 15:52:00,2020-09-22 15:52:00,11151.00,11162.149520,11162.128149,2.595571,11152.25,-11.128149,0.099987,0.099795,NaN,NaN,NaN,NaN
2020-09-22 15:53:00,2020-09-22 15:53:00,11152.25,11163.264261,11163.240110,2.574301,NaN,-10.990110,0.098763,0.098546,NaN,NaN,NaN,NaN

In [164]:
# 5.0
df6 = df5.loc[(df5['action']=='buy') | (df5['action']=='sell') | (df5['action']=='cut')]
df6.columns = ['time', 'last', 'predict1(T+1)', 'predict1(T+5)', 'atr', 'predict2(T+1)', 'adjust', 'p-percent1', 'p-percent5', 'action', 'cash', 'profit', 'message']
df6['cash'] = df6['cash'].round(4)
# 5.1 
if direction == 'long':
    no_trade = df6.loc[(df6['action']=='buy')].shape[0]
elif direction == 'short':
    no_trade = df6.loc[(df6['action']=='sell')].shape[0]
total_profit = df6.iloc[-1]['cash'].round(2)
avg_profit = df6['profit'].mean().round(2)
max_win = df6['profit'].max().round(2)
max_loss = df6['profit'].min().round(2)
no_win = int(np.sum(df6['profit'] > 0))
no_loss = int(np.sum(df6['profit'] <= 0))
no_cut_loss = int(np.sum(df6['action'] == 'cut'))
no_total_day = len(df5.groupby(df5['udate'].dt.date).size())
no_trade_day = len(df5.groupby(df6['time'].dt.date).size())
avg_no_trade = round(no_trade/no_total_day, 2)

# 5.2 加颜色
for k5, v5 in df6.iterrows():
    # 5.3 profit
    if df6.loc[k5, 'profit'] > 0:
        df6.loc[k5, 'profit'] = '<font class="text-danger">+'+str(df6.loc[k5, 'profit'])+'</font>'
    elif df6.loc[k5, 'profit'] <= 0:
        df6.loc[k5, 'profit'] = '<font class="text-success">'+str(df6.loc[k5, 'profit'])+'</font>'
    # 5.4 cash
    if df6.loc[k5, 'cash'] > 0:
        df6.loc[k5, 'cash'] = '<font class="text-danger">+'+str(df6.loc[k5, 'cash'])+'</font>'
    elif df6.loc[k5, 'cash'] <= 0:
        df6.loc[k5, 'cash'] = '<font class="text-success">'+str(df6.loc[k5, 'cash'])+'</font>'
html = df6.to_html(classes='table table-sm table-striped', index=False, escape=False, border=0).replace('border="1"', 'border="0"').replace('NaN', '')
data4 = {'total_profit': total_profit, 'avg_profit': avg_profit, 'max_win': max_win, 'max_loss': max_loss,
         'no_trade': no_trade, 'no_win': no_win, 'no_loss': no_loss, 'no_cut_loss': no_cut_loss, 'avg_no_trade': avg_no_trade, 'no_total_day': no_total_day,
         'html': html}
data5 = json.dumps(data4)

del data4['html']
print(data4)
df6

{'total_profit': 13107.4, 'avg_profit': 34.68, 'max_win': 1050.8, 'max_loss': -864.2, 'no_trade': 378, 'no_win': 217, 'no_loss': 161, 'no_cut_loss': 377, 'avg_no_trade': 3.44, 'no_total_day': 55}

,time,last,predict1(T+1),predict1(T+5),atr,predict2(T+1),adjust,p-percent1,p-percent5,action,cash,profit,message
udate,,,,,,,,,,,,,
2020-06-10 14:02:00,2020-06-10 14:02:00,10053.00,10097.510259,10098.496268,4.059217,10065.00,-45.496268,0.442756,0.452564,buy,NaN,NaN,NaN
2020-06-10 14:03:00,2020-06-10 14:03:00,10065.00,10096.345888,10097.353583,4.342816,10059.50,-32.353583,0.311435,0.321446,cut,"<font class=""text-danger"">+235.8</font>","<font class=""text-danger"">+235.8</font>",NaN
2020-06-11 08:38:00,2020-06-11 08:38:00,9870.75,9919.088739,9920.020878,3.698784,9876.00,-49.270878,0.489717,0.499160,buy,NaN,NaN,NaN
2020-06-11 08:39:00,2020-06-11 08:39:00,9876.00,9913.671282,9914.617821,3.914899,9879.00,-38.617821,0.381443,0.391027,cut,"<font class=""text-danger"">+336.6</font>","<font class=""text-danger"">+100.8</font>",NaN
2020-06-11 09:59:00,2020-06-11 09:59:00,9881.75,9927.490383,9927.877397,4.095477,9867.00,-46.127397,0.462877,0.466794,buy,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-16 14:11:00,2020-09-16 14:11:00,11285.75,11344.892854,11345.874181,5.955010,11292.75,-60.124181,0.524049,0.532744,cut,"<font class=""text-danger"">+12555.8</font>","<font class=""text-success"">-179.2</font>",NaN
2020-09-16 14:32:00,2020-09-16 14:32:00,11240.75,11292.221804,11292.829914,6.315408,11252.50,-52.079914,0.457904,0.463314,buy,NaN,NaN,NaN
2020-09-16 14:33:00,2020-09-16 14:33:00,11252.50,11287.141854,11287.725443,6.589858,11268.75,-35.225443,0.307859,0.313045,cut,"<font class=""text-danger"">+12786.6</font>","<font class=""text-danger"">+230.8</font>",NaN
2020-09-17 09:25:00,2020-09-17 09:25:00,11015.50,11070.514008,11071.018661,8.643143,11014.50,-55.518661,0.499424,0.504005,buy,NaN,NaN,NaN
2020-09-17 09:28:00,2020-09-17 09:28:00,11031.75,11051.017261,11051.429236,8.647423,11037.25,-19.679236,0.174653,0.178387,cut,"<font class=""text-danger"">+13107.4</font>","<font class=""text-danger"">+320.8</font>",NaN